const CONFIG_MAPS_ENDPOINT = 'configmaps';
const CRON_JOBS_ENDPOINT = 'cronjobs';
const CLUSTER_EVENTS_ENDPOINT = 'events';
const DAEMON_SETS_ENDPOINT = 'daemonsets';
const DEPLOYMENT_ENDPOINT = 'deployments';
const JOBS_ENDPOINT = 'jobs';
const NAMESPACES_ENDPOINT = 'namespaces';
const PODS_ENDPOINT = 'pods';
const REPLICA_SETS_ENDPOINT = 'replicasets';
const STATEFUL_SETS_ENDPOINT = 'statefulsets';
const CONFIG_ENDPOINT = '/app/config';
const API_VERSION = '/api/v1';
const SECRETS_ENDPOINT = 'secrets';
const HPA_ENDPOINT = 'horizontalpodautoscalers';
const LIMIT_RANGE_ENDPOINT = 'limitranges';
const RESOURCE_QUOTAS_ENDPOINT = 'resourcequotas';
const SERVICE_ACCOUNTS_ENDPOINT = 'serviceaccounts';
const ROLES_ENDPOINT = 'roles';
const ROLE_BINDINGS_ENDPOINT = 'rolebindings';
const CLUSTER_ROLES_ENDPOINT = 'clusterroles';
const CLUSTER_ROLE_BINDINGS_ENDPOINT = 'clusterrolebindings';
const PERSISTENT_VOLUMES_ENDPOINT = 'persistentvolumes';
const PERSISTENT_VOLUME_CLAIMS_ENDPOINT = 'persistentvolumeclaims';
const STORAGE_CLASSES_ENDPOINT = 'storageclasses';
const PRIORITY_CLASSES_ENDPOINT = 'priorityclasses';
const LEASES_ENDPOINT = 'leases';
const RUNTIME_CLASSES_ENDPOINT = 'runtimeclasses';
const POD_DISRUPTION_BUDGETS_ENDPOINT = 'poddisruptionbudgets';
const SERVICES_ENDPOINT = 'services';
const INGRESSES_ENDPOINT = 'ingresses';
const ENDPOINTS_ENDPOINT = 'endpoints';
const PORT_FORWARDING_ENDPOINT = 'portforwards';
const CUSTOM_RESOURCES_ENDPOINT = 'customresourcedefinitions';
const CUSTOM_RESOURCES_LIST_ENDPOINT = 'customresources';
const KUBECONFIGS_BEARER_URL = 'kubeconfigs-bearer';
const KUBECONFIGS_CERTIFICATE_URL = 'kubeconfigs-certificate';
const KUBECONFIGS_URL = 'kubeconfigs';
const NODES_ENDPOINT = 'nodes';
const MCP_SERVER_ENDPOINT = '/mcp/llm/v1';



export {
  API_VERSION,
  CONFIG_ENDPOINT,
  CONFIG_MAPS_ENDPOINT,
  CRON_JOBS_ENDPOINT,
  CLUSTER_EVENTS_ENDPOINT,
  DAEMON_SETS_ENDPOINT,
  DEPLOYMENT_ENDPOINT,
  JOBS_ENDPOINT,  
  NAMESPACES_ENDPOINT,
  PODS_ENDPOINT,
  REPLICA_SETS_ENDPOINT,
  STATEFUL_SETS_ENDPOINT,
  SECRETS_ENDPOINT,
  HPA_ENDPOINT,
  LIMIT_RANGE_ENDPOINT,
  RESOURCE_QUOTAS_ENDPOINT,
  SERVICE_ACCOUNTS_ENDPOINT,
  ROLES_ENDPOINT,
  ROLE_BINDINGS_ENDPOINT,
  CLUSTER_ROLES_ENDPOINT,
  CLUSTER_ROLE_BINDINGS_ENDPOINT,
  PERSISTENT_VOLUMES_ENDPOINT,
  PERSISTENT_VOLUME_CLAIMS_ENDPOINT,
  STORAGE_CLASSES_ENDPOINT,
  PRIORITY_CLASSES_ENDPOINT,
  LEASES_ENDPOINT,
  RUNTIME_CLASSES_ENDPOINT,
  POD_DISRUPTION_BUDGETS_ENDPOINT,
  SERVICES_ENDPOINT,
  INGRESSES_ENDPOINT,
  ENDPOINTS_ENDPOINT,
  PORT_FORWARDING_ENDPOINT,
  CUSTOM_RESOURCES_ENDPOINT,
  CUSTOM_RESOURCES_LIST_ENDPOINT,
  KUBECONFIGS_URL,
  KUBECONFIGS_BEARER_URL,
  KUBECONFIGS_CERTIFICATE_URL,
  NODES_ENDPOINT,
  MCP_SERVER_ENDPOINT
};
