package crds

import (
	"fmt"
	"strings"
)

var iconsList = []string{
	"aiven.io",
	"amazonaws.com",
	"ansible.com",
	"apache.org",
	"argoproj.io",
	"banzaicloud.com",
	"bitnami.com",
	"cert-manager.io",
	"cilium.io",
	"cloudflare-operator.io",
	"cloudflare.com",
	"cncf.io",
	"confluent.io",
	"coreos.com",
	"crossplane.io",
	"dapr.io",
	"datadoghq.com",
	"doppler.com",
	"dragonflydb.io",
	"dynatrace.com",
	"elastic.co",
	"emqx.io",
	"envoyproxy.io",
	"external-secrets.io",
	"f5.com",
	"flagger.app",
	"fluent.io",
	"fluxcd.io",
	"getambassador.io",
	"github.com",
	"github.io",
	"gitlab.com",
	"gke.io",
	"google.com",
	"grafana.com",
	"hashicorp.com",
	"hivemq.com",
	"istio.io",
	"jaegertracing.io",
	"jfrog.com",
	"k0sproject.io",
	"k6.io",
	"k8s.aws",
	"k8s.io",
	"k8up.io",
	"karpenter.sh",
	"keda.sh",
	"keycloak.org",
	"konghq.com",
	"kserve.io",
	"kubeflow.org",
	"kyverno.io",
	"linkerd.io",
	"longhorn.io",
	"mariadb.com",
	"metallb.io",
	"min.io",
	"mongodb.com",
	"nats.io",
	"nginx.org",
	"onepassword.com",
	"openshift.io",
	"openshift",
	"opentelemetry.io",
	"oracle.com",
	"oraclecloud.com",
	"pingcap.com",
	"projectcontour.io",
	"rabbitmq.com",
	"redislabs.com",
	"rook.io",
	"scylladb.com",
	"solo.io",
	"strimzi.io",
	"teleport.dev",
	"temporal.io",
	"tinkerbell.org",
	"traefik.io",
	"velero.io",
	"x-k8s.io",
	"zalan.do",
}

func resolveIcons(groupName string) string {
	for _, v := range iconsList {
		if strings.Contains(groupName, v) {
			return fmt.Sprintf("%s.svg", v)
		}
	}
	return ""
}
