package crds

import (
	"fmt"
	"strings"
)

var iconsList = map[string][]string{
	"aiven.io":                   {"aiven.io"},
	"amazonaws.com":              {"amazonaws.com"},
	"ansible.com":                {"ansible.com"},
	"apache.org":                 {"apache.org"},
	"argoproj.io":                {"argoproj.io"},
	"banzaicloud.com":            {"banzaicloud.com"},
	"bitnami.com":                {"bitnami.com"},
	"cert-manager.io":            {"cert-manager.io"},
	"chaos-mesh.org":             {"chaos-mesh.org"},
	"cilium.io":                  {"cilium.io"},
	"clastix.io":                 {"clastix.io"},
	"cloudflare-operator.io":     {"cloudflare-operator.io"},
	"cloudflare.com":             {"cloudflare.com"},
	"cncf.io":                    {"cncf.io"},
	"cnpg.io":                    {"cnpg.io"},
	"confluent.io":               {"confluent.io"},
	"coreos.com":                 {"coreos.com"},
	"crossplane.io":              {"crossplane.io"},
	"dapr.io":                    {"dapr.io"},
	"datadoghq.com":              {"datadoghq.com"},
	"doppler.com":                {"doppler.com"},
	"dragonflydb.io":             {"dragonflydb.io"},
	"dynatrace.com":              {"dynatrace.com"},
	"elastic.co":                 {"elastic.co"},
	"emqx.io":                    {"emqx.io"},
	"envoyproxy.io":              {"envoyproxy.io"},
	"external-secrets.io":        {"external-secrets.io"},
	"f5.com":                     {"f5.com"},
	"falco.org":                  {"falco.org"},
	"flagger.app":                {"flagger.app"},
	"fluent.io":                  {"fluent.io"},
	"fluxcd.io":                  {"fluxcd.io"},
	"getambassador.io":           {"getambassador.io"},
	"github.com":                 {"github.com"},
	"github.io":                  {"github.io"},
	"gitlab.com":                 {"gitlab.com"},
	"gke.io":                     {"gke.io"},
	"goharbor.io":                {"goharbor.io"},
	"google.com":                 {"google.com"},
	"grafana.com":                {"grafana.com"},
	"hashicorp.com":              {"hashicorp.com"},
	"hivemq.com":                 {"hivemq.com"},
	"istio.io":                   {"istio.io"},
	"jaegertracing.io":           {"jaegertracing.io"},
	"jfrog.com":                  {"jfrog.com"},
	"k0sproject.io":              {"k0sproject.io"},
	"k6.io":                      {"k6.io"},
	"k8s.aws":                    {"k8s.aws"},
	"k8s.io":                     {"k8s.io"},
	"k8up.io":                    {"k8up.io"},
	"karpenter.sh":               {"karpenter.sh"},
	"keda.sh":                    {"keda.sh"},
	"keycloak.org":               {"keycloak.org"},
	"knative.dev":                {"knative.dev"},
	"konghq.com":                 {"konghq.com"},
	"kserve.io":                  {"kserve.io"},
	"kubeflow.org":               {"kubeflow.org"},
	"kubevirt.io":                {"kubevirt.io"},
	"kyverno.io":                 {"kyverno.io"},
	"linkerd.io":                 {"linkerd.io"},
	"litmuschaos.io":             {"litmuschaos.io"},
	"longhorn.io":                {"longhorn.io"},
	"mariadb.com":                {"mariadb.com"},
	"metallb.io":                 {"metallb.io"},
	"microsoft.com":              {"microsoft.com"},
	"min.io":                     {"min.io"},
	"mongodb.com":                {"mongodb.com"},
	"nats.io":                    {"nats.io"},
	"nginx.org":                  {"nginx.org"},
	"nvidia.com":                 {"nvidia.com", "nvidia.io"},
	"onepassword.com":            {"onepassword.com"},
	"open-cluster-management.io": {"open-cluster-management.io"},
	"openebs.io":                 {"openebs.io"},
	"openshift.io":               {"openshift.io"},
	"openshift":                  {"openshift"},
	"opentelemetry.io":           {"opentelemetry.io"},
	"oracle.com":                 {"oracle.com"},
	"oraclecloud.com":            {"oraclecloud.com"},
	"pingcap.com":                {"pingcap.com"},
	"projectcalico.org":          {"projectcalico.org"},
	"projectcontour.io":          {"projectcontour.io"},
	"rabbitmq.com":               {"rabbitmq.com"},
	"ray.io":                     {"ray.io"},
	"redislabs.com":              {"redislabs.com"},
	"rook.io":                    {"rook.io"},
	"scylladb.com":               {"scylladb.com"},
	"solo.io":                    {"solo.io"},
	"strimzi.io":                 {"strimzi.io"},
	"tekton.dev":                 {"tekton.dev"},
	"teleport.dev":               {"teleport.dev"},
	"temporal.io":                {"temporal.io"},
	"tinkerbell.org":             {"tinkerbell.org"},
	"traefik.io":                 {"traefik.io"},
	"velero.io":                  {"velero.io"},
	"victoriametrics.com":        {"victoriametrics.com"},
	"volcano.sh":                 {"volcano.sh"},
	"x-k8s.io":                   {"x-k8s.io"},
	"zalan.do":                   {"zalan.do"},
}

func resolveIcons(input string) string {
	for group, aliases := range iconsList {
		for _, alias := range aliases {
			if strings.Contains(input, alias) {
				return fmt.Sprintf("%s.svg", group)
			}
		}
	}
	return ""
}
