apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubewall.fullname" . }}
  labels:
    {{- include "kubewall.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "kubewall.listenPort" . | int }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "kubewall.selectorLabels" . | nindent 4 }}
